/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteDetailRouteImport } from './routes/site-detail'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as MapRouteImport } from './routes/map'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteSiteIdRouteImport } from './routes/site.$siteId'

const SiteDetailRoute = SiteDetailRouteImport.update({
  id: '/site-detail',
  path: '/site-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSiteIdRoute = SiteSiteIdRouteImport.update({
  id: '/site/$siteId',
  path: '/site/$siteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/dispatch': typeof DispatchRoute
  '/map': typeof MapRoute
  '/risk': typeof RiskRoute
  '/site-detail': typeof SiteDetailRoute
  '/site/$siteId': typeof SiteSiteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/dispatch': typeof DispatchRoute
  '/map': typeof MapRoute
  '/risk': typeof RiskRoute
  '/site-detail': typeof SiteDetailRoute
  '/site/$siteId': typeof SiteSiteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRoute
  '/dispatch': typeof DispatchRoute
  '/map': typeof MapRoute
  '/risk': typeof RiskRoute
  '/site-detail': typeof SiteDetailRoute
  '/site/$siteId': typeof SiteSiteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decisions'
    | '/dispatch'
    | '/map'
    | '/risk'
    | '/site-detail'
    | '/site/$siteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/decisions'
    | '/dispatch'
    | '/map'
    | '/risk'
    | '/site-detail'
    | '/site/$siteId'
  id:
    | '__root__'
    | '/'
    | '/decisions'
    | '/dispatch'
    | '/map'
    | '/risk'
    | '/site-detail'
    | '/site/$siteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecisionsRoute: typeof DecisionsRoute
  DispatchRoute: typeof DispatchRoute
  MapRoute: typeof MapRoute
  RiskRoute: typeof RiskRoute
  SiteDetailRoute: typeof SiteDetailRoute
  SiteSiteIdRoute: typeof SiteSiteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/site-detail': {
      id: '/site-detail'
      path: '/site-detail'
      fullPath: '/site-detail'
      preLoaderRoute: typeof SiteDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$siteId': {
      id: '/site/$siteId'
      path: '/site/$siteId'
      fullPath: '/site/$siteId'
      preLoaderRoute: typeof SiteSiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecisionsRoute: DecisionsRoute,
  DispatchRoute: DispatchRoute,
  MapRoute: MapRoute,
  RiskRoute: RiskRoute,
  SiteDetailRoute: SiteDetailRoute,
  SiteSiteIdRoute: SiteSiteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
